### ISSUE TITLE
Sitemap tidak menampilkan halaman yang tanpa page-child

### ISSUE THREAD

**Issue by bungfrangki** [mecha-cms/x.sitemap#2]
### Make sure that your issue is reproducible by doing the following tasks

- [X] I am using application packages whose source code is not optimized for production (source code is not minified).
- [X] I have activated the test mode by changing the `TEST` constant value to `true` in the `.\index.php` file.
- [X] I have made sure that there are files named `error` or `error-x` or `error-y` in the `.\engine\log` folder.

### What installation method did you use?

File

### Describe your issue in the field below

saat membuka /sitemap.xml yang ditampilkan hanyalah page-parent (/foo/sitemap.xml), sementara saya punya beberapa halaman yang tanpa page-child/folder (seperti halaman Contact, About, Pribacy Policy, Disclaimer, dll)
![sitemap-mecha-csm](https://github.com/mecha-cms/x.sitemap/assets/19464438/491280f2-c62b-4d0d-b9f4-cda347f80e01)

catatan:
btw, saya menggunakan Mecha CMS 3.0, dan sitemap main ambil langsung dari github. Tapi ada lakukan sedikit modifikasi pada file indexnya, saya ganti \lot() menjadi $GLOBALS, kalau gak gitu web dapat pesan error 500

### Package version

Development version (package on the `main` branch)

### Package version number

main

### What browsers are you seeing the problem on?

Chrome

**Comment by taufik-nurrohman** [comment]
Kalau untuk menambahkan item-item laman statis ke dalam sitemap utama kemungkinan tidak bisa mas karena item-item indeks tidak boleh dicampur dengan item-item tautan [^1]

Tapi nanti bisa diakali dengan cara menambah tautan indeks sitemap khusus untuk menge-list daftar laman yang tidak memiliki anak laman. Misalnya sebagai `http://example.com/-/sitemap.xml`

[^1]: https://webmasters.stackexchange.com/a/130907

**Comment by bungfrangki** [comment]
ya itu maksud saya, menambahkan tautan khusus pada indeks sitemap. cuma saya bingung menerapkan kondisinya.
saat ini saya menggunakan cara yg sangat primitif dengan menambahkan kode ini di sitemap index:

```
$content .= '<sitemap>';
$content .= '<loc>' . \Hook::fire('link', [$url.'/sitemap-web.xml']) . '</loc>';
$content .= '<lastmod>' . \date('c', \filemtime($kk)) . '</lastmod>';
$content .= '</sitemap>';
```
adapun file `sitemap-web.xml` hasil convert dari sitemap generator lalu di upload ke hostingan hehehe
